name: Deploy work flow for AWS Elastic Container Service

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  REPOSITORY_NAME: twitter-clone-ecs
  TASK_NAME: twitter-clone
  ECS_SERVICE_NAME: twitter-clone-service
  ECS_CLUSTER_NAME: twitter-clone-cluster
  LAUNCH_TYPE: FARGATE

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout # githubのコードを取得
        uses: actions/checkout@v6

      - name: Configure AWS credentials # AWS側でOIDCでロールを使ってリソースを動かせるようにする
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Login to ECR # ECRにログインする
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: rails-app push to ECR # イメージ化したコンテナ情報をECRへPushする
        id: build-image-rails-app
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --platform linux/amd64 -t ${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}:latest .
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}:latest

      - name: Update task definition image # タスク定義を取得してイメージ部分を書き換えたJSONを新しいタスク定義として作成
        id: update-task-definition
        env:
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY_NAME }}:latest
        run: |
          aws ecs describe-task-definition \
          --task-definition "$TASK_NAME" \
          --query 'taskDefinition' \
          --output json > current_task_def.json

          jq --arg twitter_clone ${{ env.IMAGE_URI }} '
            .containerDefinitions |= (
              map(
                if .name = "twitter_clone"
                then .image = $twitter_clone
                else .
                end
              )
            )
            | del(.revision, .status, .requiresAttributes, .compatibilities, .taskDefinitionArn, .registeredAt, .registeredBy)
          ' current_task_def.json > new_task_def.json
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://new_task_def.json \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)
          echo "NEW_TASK_DEF_ARN=$NEW_TASK_DEF_ARN" >> "$GITHUB_OUTPUT"

      - name: Run database migration # 更新したタスクでECSを再デプロイする前にマイグレーションを実行
        run: |
          aws ecs run-task \
            --cluster $ECS_CLUSTER_NAME \
            --launch-type $LAUNCH_TYPE \
            --task-definition ${{ steps.update-task-definition.outputs.NEW_TASK_DEF_ARN }}\
            --network-configuration "awsvpcConfiguration={subnets=[subnet-0e52ed5e61c3be380, subnet-0dff4ab6d1ff1bc24], securityGroups=[sg-0bace422ef1b18d88],assignPublicIp=ENABLED}" \
            --overrides '{
              "containerOverrides":[
                  {
                    "name":"rails-app",
                    "command":["bundle", "exec", "rails", "db:migrate"],
                    "environment":[
                        {"name":"RAILS_ENV", "value":"production"},
                        {"name":"DATABASE_URL","value":"${{ secrets.DATABASE_URL }}"}
                      ]
                  }
                ]
            }'

      - name: Deploy to ECS # 書き換えたタスク定義を元にECSのコンテナを起動し直す
        run: |
          aws ecs update-service \
          --cluster $ECS_CLUSTER_NAME \
          --service $ECS_SERVICE_NAME \
          --task-definition "${{ steps.update-task-definition.outputs.NEW_TASK_DEF_ARN }}" \
          --force-new-deployment
